from character import *

main_character = MainChar("Vitalik")
print(main_character.name,'\'s hp = ',main_character.health)
potion = HealingPotion('Healing Potion', 1)
main_character.backpack.add_item(potion)
main_character.backpack.add_item(potion)
royal = Item('Piano', 20)
main_character.backpack.add_item(royal)
main_character.take_damage(50)
potion.using(main_character)
print(main_character.name,'\'s hp =',main_character.health)
print('Equipping "Helm of Iron Will"')
helm_oiw = Helmets('Helm of Iron Will', 4)
helm_kek = Helmets('Helm of KEK', 4)
main_character.equip_item_helm(helm_oiw)
print(main_character.equipment)
main_character.print_stats()
main_character.equip_item_helm(helm_kek)
print(main_character.equipment)
main_character.print_stats()